### ISSUE TITLE
Trace functionality docs

### ISSUE THREAD

**Issue by manishas** [Shippable/docsv2#590]
https://github.com/Shippable/pm/issues/7036

Please provide a draft with screenshots on how Trace functionality works so we can include it in docs.

**Comment by stephanielingwood** [comment]
### Trace

The trace view shows the inputs to a given job. To get to the trace view, click on a job in the SPOG to open the console. Next, click the "trace" button on the left-hand side. This opens a list of the job's inputs; you can then drill down to see what those inputs are made of.

Let's say you created a release, and now want to see what, exactly, the release contains. When you click trace, the list shows the inputs to that release job:

![tracereleaseview](https://cloud.githubusercontent.com/assets/7757711/21117775/fd1f7a5a-c06f-11e6-9f02-4fa0e530b1f4.png)

Here, the release has two inputs: a deploy job (`deploy-pipelines-demo`), and a version resource (`pipelines-demo-version`). To see what the deploy is made of, click the arrow icon to show the inputs to that deploy job:

![tracedeployview](https://cloud.githubusercontent.com/assets/7757711/21117781/0276a460-c070-11e6-9df6-5ecb3125bef6.png)

This deploy job has three inputs: `docker-options`, `ecs-cluster`, and `pipelines-demo-manifest`. Since the manifest will have the details on the images being deployed, let's look at that:

![tracemanifestview](https://cloud.githubusercontent.com/assets/7757711/21117795/0bd490f8-c070-11e6-9231-ad04d045e4d9.png)

Great - the release job contains `pipelines-demo-image`, and the image tag is `master.9`. But what's in `master.9`? Clicking on `master.9` takes you to the CI job that created and pushed the image:

![tracecijobview](https://cloud.githubusercontent.com/assets/7757711/21117801/107daa0e-c070-11e6-8d64-e122fa1c6a35.png)

Finally, clicking on the `Sha` link takes you to that commit on the source provider. Congratulations! You've traced a release back to its source code, all in just a few clicks.

**Comment by stephanielingwood** [comment]
@manishas ^^^

**Comment by trriplejay** [comment]
This is in prod docs. closing.
